import 'dotenv/config';

export const {
    APP_NAME,
    PORT = 4000,
    IPBIND = '127.0.0.1',
    JWT_ACCESS_EXPIRATION = '1h',
    JWT_REFRESH_EXPIRATION = '1d',
    FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID,
    FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL,
} = process.env;
